menu:
  Home: /
  Archives: /archives
  Profile: /profile
  RSS: /atom.xml

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: _ytanaka_
  show_replies: true
  tweet_count: 5

addthis:
  enable: true
  pubid: 54154819
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss: /atom.xml
